apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: compute-deployment
  labels:
    app: compute-app
    type: back-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: compute-app
  template:
    metadata:
      name: compute-pod
      labels:
        app: compute-app
        type: back-end
    spec:
      containers:
        - name: my-compute
          image: aggarwalmayank/compute-image:latest
          ports:
            - containerPort: 8080
